/* Views for the real workbook ledger; never mix in sample market/research data. */
function paperView(tab) {
 const p=paperResult, s=p.audit.settings;
 const checks=()=>table(['Rule','Actual','Limit','Status'],p.risk.checks.map(c=>[SettingsModel.fields.find(f=>f[0]===c.id)[1],num(c.value),num(c.limit),esc(c.status)]));
 const flags=p.warnings.map(w=>notice(esc(w.securityId?`${w.securityId}: ${w.code.replaceAll('_',' ').toLowerCase()}${w.date?' ('+w.date+')':''}`:w.message||w.code))).join('');
 const settingsRows=[['Initial cash',money(s.initialCash)],['Inception',esc(s.inception)],['Review status',esc(s.status)],['Permitted instruments',esc(s.allowed.join(', ')||'Cash only')]];
 switch(tab) {
 case 'overview':return card('Google Sheets paper portfolio',`<div class="stats">${stat('NAV',money(p.nav))}${stat('Total P&L',money(p.totalPnl),'Since inception; includes income and fees')}${stat('Settled cash',money(p.cash))}${stat('Receivables',money(p.receivables),'Unsettled sales')}${stat('Liabilities',money(p.liabilities),'Unsettled purchases')}${stat('Holdings',String(p.positions.length))}</div>`,esc(p.asOf))+flags+
  card('NAV reconciliation',table(['Component','USD'],[['Market value',p.invested],['Settled cash',p.cash],['Receivables',p.receivables],['Liabilities',-p.liabilities],['NAV',p.nav]].map(([a,b])=>[a,money(b)])))+
  card('P&L reconciliation',table(['Component','USD'],[['Realized gain (FIFO)',p.realizedGain],['Unrealized gain',p.unrealizedGain],['Income',p.income],['Financing expenses',-p.expenses],['Total P&L',p.totalPnl],['Net contributions',p.netContributions],['Reconciliation difference',p.reconciliationDifference]].map(([a,b])=>[a,money(b)])))+
  card('Recorded NAV history','<p>No saved history yet. Refresh calculates current values without inventing past observations.</p>');
 case 'book':return card('Book — workbook holdings',notice('FIFO dirty cost includes purchase fees and execution accrued interest. Market value includes supplied mark accrued interest. Gains are not clean-price attribution.')+`<div id="bookTable">${table(['Security','Issuer','Instrument','Rating','Size','Price','YTM','YTW','Duration','Market value','Unrealized gain','Mark date','Maturity'],p.positions.map(x=>[esc(x.id)+'<span class="pname">'+esc(x.name)+'</span>',esc(x.issuer),esc(x.instrument),esc(x.rating),num(x.quantity)+' '+esc(x.quantityType),num(x.price),pct(x.ytm),pct(x.ytw),num(x.duration),money(x.marketValue),money(x.unrealizedGain),esc(x.markDate),esc(x.maturityDate||'—')]))}</div>`+(p.positions.length?'':'<p>No executed positions. Add security records, trades and marks to the workbook.</p>'));
 case 'risk':return card('Workbook risk',notice('First-order sensitivity using supplied durations. Missing analytics remain unknown. Futures and calibrated VaR are not implemented.')+`<div class="stats">${stat('Duration',num(p.risk.values.duration)+' yrs')}${stat('Spread duration',num(p.risk.values.spreadDuration)+' yrs')}${stat('Rate DV01',money(p.risk.dv01)+'/bp')}${stat('Spread DV01',money(p.risk.sdv01)+'/bp')}</div>`)+flags+
  card('Parallel rate scenarios',table(['Yield change','Estimated P&L'],[-100,-50,-25,25,50,100].map(b=>[b+' bp',money(p.risk.dv01===null?null:-p.risk.dv01*b)])));
 case 'limits':return card('Workbook limits',checks()+p.risk.permissionBreaches.map(id=>notice(esc(id)+' is not permitted.')).join('')+notice('UNKNOWN means the inputs are insufficient to assess the limit; it is not a pass.'));
 case 'settings':return card('Shared workbook settings',notice('These settings come from the Limits tab. Edit them in Google Sheets, then Refresh. Browser-local sample settings do not override them.')+table(['Setting','Value'],settingsRows)+checks()+`<p><a href="https://docs.google.com/spreadsheets/d/${GoogleSheetsPortfolio.spreadsheetId}/edit" target="_blank" rel="noopener">Open the workbook</a></p>`);
 case 'calendar':return card('Trade settlements',table(['Trade','Security','Settlement date','Cash movement','Status'],p.settlements.map(x=>[esc(x.tradeId),esc(x.securityId),esc(x.date),money(x.amount),x.settled?'Settled':'Outstanding'])))+card('Bond maturities',table(['Security','Maturity'],p.positions.filter(x=>x.maturityDate).map(x=>[esc(x.id),esc(x.maturityDate)]))+notice('Maturity dates are reference records. Automatic redemption and coupon scheduling are not implemented.'));
 case 'credit':return card('Credit holdings',table(['Security','Issuer','Rating','Market value','Spread duration'],p.positions.filter(x=>x.instrument==='CORP'||(x.instrument==='ETF'&&x.spreadDuration!==0)).map(x=>[esc(x.id),esc(x.issuer),esc(x.rating),money(x.marketValue),num(x.spreadDuration)]))+notice('Unrated credit exposure produces unknown rating-based limits.'));
 case 'macro':return card('Treasury curve','<p>A live Treasury curve feed has not been connected. Workbook marks are used for valuation.</p>');
 case 'research':return card('Research','<p>Trade thesis links are stored in the Trades tab. A research feed has not been connected.</p>');
 }
}
