const {readFileSync}=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const source=readFileSync('settings.js','utf8');
const context=vm.createContext({localStorage:{getItem:()=>null}});
vm.runInContext(source,context);
vm.runInContext(`globalThis.model=SettingsModel`,context);
const m=context.model;
assert.equal(m.assess(4.9,5,true),'BREACH');
assert.equal(m.assess(5,5,true),'WATCH');
assert.equal(m.assess(0,0,true),'OK');
assert.equal(m.assess(0.01,0),'BREACH');
assert.equal(m.assess(5.1,6),'WATCH');
assert.equal(m.assess(6,6),'WATCH');
assert.equal(m.assess(6.01,6),'BREACH');
for(const change of [{initialCash:0},{initialCash:NaN},{inception:'2026-02-30'},{allowed:['UNKNOWN']},{status:'invalid'},{limits:{}}]) assert.throws(()=>m.validate({...m.defaults(),...change}));
assert.equal(m.validate({...m.defaults(),allowed:[]}).allowed.length,0);
const html=readFileSync('index.html','utf8');
new vm.Script(readFileSync('app.js','utf8'));
new vm.Script(readFileSync('model.js','utf8'));
console.log('Settings validation, boundary checks, and dashboard syntax passed.');
